### ISSUE TITLE
$ parsing

### ISSUE THREAD

**Issue by wulfygrl** [john-guo/columnpaste#6]
If the copied text contains a $-delimited variable like `$VAR`, it is deleted on paste. I assume that these would instead paste internal variable values if the names matched, but not sure what scope they would be from so I can't test that.

Reproduce:
Highlight `Second` text below and columnpaste next to `First`
```
First       
$C1VAR1     
$C1VAR2     

Second
$C2VAR1
$C2VAR2
```
Expected Result:
```
First       Second
$C1VAR1     $C2VAR1
$C1VAR2     $C2VAR2
```
Actual Result:
```
First       Second
$C1VAR1     
$C1VAR2     
```
Workaround:
Escape all `$`s before copying:
```
First       
$C1VAR1     
$C1VAR2     

Second
\$C2VAR1
\$C2VAR2
```

**Comment by john-guo** [comment]
Yes, this is a problem, I will fix it in 0.0.7 version. Thank you for this issue.
