### ISSUE TITLE
Not working after recent update

### ISSUE THREAD

**Issue by Scorg** [john-guo/columnpaste#9]
Tried on vscode version 1.75.0

Both paste options only paste text from first line of the copied text. To insert all lines you have to select multiple positions, equal to the number of lines copied (which is supported by basic vscode without this extension).

**Comment by john-guo** [comment]
Yes, it's an issue on the 1.75.0. The vscode team change the behavior of a crucial method. I have published a new version 0.0.8 of this extension. Thank you.
